import Head from 'next/head';
import React from 'react';
import HeaderReservas from '../components/HeaderReservas';
import Footer from '../components/Footer';
import Carousel from '@/components/Carousel';
import MyPlace from '@/components/MyPlace';
import styles from '../styles/home.module.css';
import Restaurantes from '@/components/Restaurantes';
import Alteração from '@/components/Alteração';

const Home: React.FC = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Alteração de dados</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.svg" type='image/svg+xml' />
      </Head>
      <header>
        <HeaderReservas />
      </header>
      <main className={styles.main}>
        <Alteração />
      </main>
      <footer className={styles.footer}>
        <Footer />
      </footer>
    </div>
  );
};

export default Home;
