import Head from 'next/head';
import Footer from '../components/Footer';
import styles from '../styles/home.module.css';
import Cadastro from '@/components/Cadastro';

const CadastroPage: React.FC = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Le Bruine</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.svg" type='image/svg+xml' />
      </Head>
      <main className={styles.main}>
        <Cadastro />
      </main>
      <footer className={styles.footer}>
        <Footer />
      </footer>
    </div>
  );
};

export default CadastroPage;
