// pages/index.tsx
import Head from 'next/head';
import Header from '../components/Header';
import Footer from '../components/Footer';
import Carousel from '@/components/Carousel';
import MyPlace from '@/components/MyPlace';
import styles from '../styles/home.module.css'; // Importando estilos CSS
import Restaurantes from '@/components/Restaurantes';

const Home: React.FC = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>My Next.js App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <Header />
      </header>
      <main className={styles.main}>
        <MyPlace />
        <Carousel />
        <Restaurantes />
      </main>
      <footer className={styles.footer}>
        <Footer />
      </footer>
    </div>
  );
};

export default Home;
