// pages/index.tsx
import Head from 'next/head';
import Header from '../components/Header';
import Footer from '../components/Footer';
import Carousel from '@/components/Carousel';

const Home: React.FC = () => {
  return (
    <div>
      <Head>
        <title>My Next.js App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <main>
        <Carousel />
      </main>
      <Footer />
    </div>
  );
};

export default Home;
