import Head from 'next/head';
import Header from '../components/Header';
import Footer from '../components/Footer';
import styles from '../styles/home.module.css';
import Login from '@/components/Login';

const LoginPage: React.FC = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.svg" type='image/svg+xml' />
      </Head>
      <main className={styles.main}>
        <Login />
      </main>
      <footer className={styles.footer}>
        <Footer />
      </footer>
    </div>
  );
};

export default LoginPage;
